#!/usr/bin/env python3
"""Generate the per-track lab files and the lab landing pages.

One source per feature lives next to this script (docs/labs/F01.md ... F10.md).
Each source produces four files in that feature's folder:

    FNN-lab.md                    short landing page: goal, input, model, track links
    dotnet/FNN-dotnet.md          the full lab, .NET flavored
    python/FNN-python.md          the full lab, Python flavored
    typescript/FNN-typescript.md  the full lab, TypeScript flavored

Edit the source, then run from the repo root:

    python3 docs/labs/build_labs.py           # regenerate everything
    python3 docs/labs/build_labs.py F05       # one feature
    python3 docs/labs/build_labs.py --check   # exit 1 if any generated file is stale

Source syntax
-------------
Plain Markdown is shared by all three tracks. A block limited to some outputs is
fenced by marker lines (leading spaces allowed, so a block can sit inside a list):

    ::: dotnet
    text only the .NET lab gets
    :::

    ::: python typescript
    text both of those labs get
    :::

Block names: dotnet, python, typescript, tracks (all three track labs but not
the landing page), landing (the landing page only). Blocks do not nest.

The first line must be the "# Lab NN: Title" heading. The landing page gets
everything before the first "##"/"###" heading (minus track-only blocks), a
generated "Pick a Track" table, and the "## What Is in This Folder" section.
Track labs get everything except "landing" blocks, with a generated line
linking the other two tracks.

Write every relative link as seen from the feature folder (where FNN-lab.md
sits). The generator adds the "../" that track labs need.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
MODULES = ROOT / "modules"

TRACKS = {
    "dotnet": (".NET", "Program.cs"),
    "python": ("Python", "main.py"),
    "typescript": ("TypeScript", "index.ts"),
}
BLOCK_NAMES = set(TRACKS) | {"tracks", "landing"}
FOLDER_SECTION = "## What Is in This Folder"

MARKER_OPEN = re.compile(r"^\s*:::\s+([a-z][a-z ]*?)\s*$")
MARKER_CLOSE = re.compile(r"^\s*:::\s*$")
FENCE = re.compile(r"^\s*(```|~~~)")
LINK = re.compile(r"\]\(([^)\s]+)\)")


def banner(source: Path) -> str:
    rel = source.relative_to(ROOT).as_posix()
    return (f"<!-- Generated by docs/labs/build_labs.py from {rel}. "
            "Edit the source and rerun; hand edits to this file are overwritten. -->")


def select(lines: list[str], target: str, source: Path) -> list[str]:
    """Keep shared lines plus lines in blocks addressed to target."""
    out: list[str] = []
    active: set[str] | None = None
    in_fence = False
    for n, line in enumerate(lines, 1):
        if not in_fence:
            m = MARKER_OPEN.match(line)
            if m:
                if active is not None:
                    sys.exit(f"{source.name}:{n}: nested block marker")
                names = set(m.group(1).split())
                unknown = names - BLOCK_NAMES
                if unknown:
                    sys.exit(f"{source.name}:{n}: unknown block name {sorted(unknown)}")
                active = names
                continue
            if MARKER_CLOSE.match(line):
                if active is None:
                    sys.exit(f"{source.name}:{n}: closing marker with no open block")
                active = None
                continue
        if FENCE.match(line):
            in_fence = not in_fence
        if active is None:
            out.append(line)
        elif target in active or (target in TRACKS and "tracks" in active):
            out.append(line)
    if active is not None:
        sys.exit(f"{source.name}: block opened and never closed")
    return out


def rebase_links(lines: list[str]) -> list[str]:
    """Prefix relative link targets with ../ (track labs sit one folder down)."""
    out, in_fence = [], False
    for line in lines:
        if FENCE.match(line):
            in_fence = not in_fence
        if not in_fence:
            def fix(m: re.Match) -> str:
                t = m.group(1)
                if re.match(r"^(https?:|mailto:|#|/)", t):
                    return m.group(0)
                return f"]({'../' + t})"
            line = LINK.sub(fix, line)
        out.append(line)
    return out


def tidy(lines: list[str]) -> str:
    """Collapse runs of blank lines (outside fences) left behind by removed blocks."""
    out, in_fence, blank = [], False, False
    for line in lines:
        if FENCE.match(line):
            in_fence = not in_fence
        if not in_fence and line.strip() == "":
            if blank:
                continue
            blank = True
        else:
            blank = False
        out.append(line.rstrip())
    return "\n".join(out).strip() + "\n"


def split_sections(lines: list[str]) -> tuple[list[str], dict[str, list[str]]]:
    """Return (preamble before first heading, {'## heading': section lines})."""
    pre: list[str] = []
    sections: dict[str, list[str]] = {}
    current: list[str] | None = None
    in_fence = False
    for line in lines:
        if FENCE.match(line):
            in_fence = not in_fence
        if not in_fence and re.match(r"^#{2,3} ", line):
            current = []
            sections.setdefault(line.strip(), current)
        if current is None:
            pre.append(line)
        else:
            current.append(line)
    return pre, sections


def build(source: Path) -> dict[Path, str]:
    code = source.stem  # F01
    matches = sorted(MODULES.glob(f"*/{code}-*/"))
    if len(matches) != 1:
        sys.exit(f"{source.name}: expected one feature folder for {code}, found {len(matches)}")
    folder = matches[0]
    lines = source.read_text().splitlines()
    if not lines or not lines[0].startswith("# "):
        sys.exit(f"{source.name}: first line must be the '# Lab NN: Title' heading")
    title, body = lines[0][2:].strip(), lines[1:]
    outputs: dict[Path, str] = {}

    # Track labs.
    for track, (label, _) in TRACKS.items():
        others = ", ".join(f"[{TRACKS[t][0]}](../{t}/{code}-{t}.md)" for t in TRACKS if t != track)
        head = [banner(source), f"# {title} ({label})", "",
                f"*You are on the {label} track. Other tracks: {others}. "
                f"Lab overview: [{code}-lab.md](../{code}-lab.md).*", ""]
        text = head + rebase_links(select(body, track, source))
        outputs[folder / track / f"{code}-{track}.md"] = tidy(text)

    # Landing page.
    pre, sections = split_sections(select(body, "landing", source))
    table = ["## Pick a Track", "",
             "Every track does the same steps against the same data and checks against the same "
             "[`expected-output.md`](expected-output.md). Each track's lab has the full steps plus "
             "the exact calls, imports, and run commands for that language.", "",
             "| Track | Open this lab | What you edit |", "|---|---|---|"]
    for track, (label, starter) in TRACKS.items():
        path = f"{track}/{code}-{track}.md"
        table.append(f"| {label} | [`{path}`]({path}) | `{track}/starter/{starter}` |")
    table += ["", "Every track has a `complete/` next to its `starter/`, which is the answer key.", ""]
    landing = [banner(source), f"# {title}", ""] + pre + [""] + table + sections.get(FOLDER_SECTION, [])
    outputs[folder / f"{code}-lab.md"] = tidy(landing)
    return outputs


def main(argv: list[str]) -> int:
    check = "--check" in argv
    wanted = [a.upper() for a in argv if not a.startswith("--")]
    sources = sorted(p for p in HERE.glob("F[0-9][0-9].md") if not wanted or p.stem in wanted)
    if not sources:
        sys.exit("no sources matched")
    stale = 0
    for source in sources:
        for path, text in build(source).items():
            rel = path.relative_to(ROOT)
            if re.search("[–—“”]", text):
                print(f"warning: {rel} contains an en/em dash or curly quote")
            current = path.read_text() if path.exists() else None
            if current == text:
                continue
            if check:
                print(f"stale: {rel}")
                stale += 1
            else:
                path.write_text(text)
                print(f"wrote: {rel}")
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
